---
name: PR checks

on:
  pull_request:

jobs:
  source_branch:
    name: Source branch checks
    runs-on: [self-hosted]
    if: ${{ (github.base_ref == 'master') && (github.head_ref != 'dev') && (startsWith(github.head_ref, 'hotfix-') != true) }}
    steps:
      - name: Check source branch
        run: |
          echo "ERROR: You can only merge to master from dev or a hotfix branch."
          exit 1
